# Generated by Django 5.1.7 on 2025-03-20 16:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_date_added_alter_contact_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 3, 20, 16, 39, 46, 419660, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
