# Generated by Django 5.1.7 on 2025-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_oauthtoken_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='refresh_token',
            field=models.CharField(),
        ),
    ]
